-d C:\Users\yusuf\Desktop\FPGA\Projects\chronometer_with_7_segment_display\impl\gwsynthesis\chronometer_with_7_segment_display.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\yusuf\Desktop\FPGA\Projects\chronometer_with_7_segment_display\src\chronometer_with_7_segment_display.cst
-cfg C:\Users\yusuf\Desktop\FPGA\Projects\chronometer_with_7_segment_display\impl\pnr\device.cfg
-sdc C:\Users\yusuf\Desktop\FPGA\Projects\chronometer_with_7_segment_display\src\chronometer_with_7_segment_display.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
