-d C:\Users\yusuf\Desktop\FPGA\Projects\WS2812_RGB_led_PWE_driver\impl\gwsynthesis\WS2812_RGB_led_PWE_driver.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\yusuf\Desktop\FPGA\Projects\WS2812_RGB_led_PWE_driver\src\WS2812_RGB_led_PWE_driver.cst
-cfg C:\Users\yusuf\Desktop\FPGA\Projects\WS2812_RGB_led_PWE_driver\impl\pnr\device.cfg
-sdc C:\Users\yusuf\Desktop\FPGA\Projects\WS2812_RGB_led_PWE_driver\src\WS2812_RGB_led_PWE_driver.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
