-d C:\Users\yusuf\Desktop\FPGA\Projects\led_counter_with_timer\impl\gwsynthesis\led_counter_with_timer.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\yusuf\Desktop\FPGA\Projects\led_counter_with_timer\src\led_counter_with_timer.cst
-cfg C:\Users\yusuf\Desktop\FPGA\Projects\led_counter_with_timer\impl\pnr\device.cfg
-sdc C:\Users\yusuf\Desktop\FPGA\Projects\led_counter_with_timer\src\led_counter_with_timer.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
